### ISSUE TITLE
Partition formatting structure

### ISSUE THREAD

**Issue by Vzzarr** [crowemi/target-s3#14]
Still me bothering you.

I tried to use this config
```
    "append_date_to_prefix": true,
    "append_date_to_prefix_grain": "day",
```
but the problem with this is that it creates partitions in the form of `year/month/day` and not `year=year/month=month/day=day`, for example: `2023/05/01` instead of `year=2023/month=05/day=01`, which is the idea day when scanning this data with other services like Redshift Spectrum.

Am I using wrongly the library and there is a parameter I'm missing or is this something that can be improved?

**Comment by Vzzarr** [comment]
and here I have the PR ready hahaha https://github.com/crowemi/target-s3/pull/15

I realised it was an easy change, let me know if it looks good to you.

It would be a great addition as it would be more compliant with partitioning standards.

**Comment by crowemi** [comment]
Looks great - thank you @Vzzarr

**Comment by ian-lewis-d** [comment]
Is this an optional setting?

'partitioning standards' are often arbitrary and `year=2023\` is not a structure we use and this is the first time I have ever seen it mentioned.

**Comment by crowemi** [comment]
@ian-lewis-d  -- yes, this is an optional config setting.

**Comment by ian-lewis-d** [comment]
Cool. I'm happy as long as I can still use `2023\06\21\` for my partitions :)
