### ISSUE TITLE
target-s3 always appends seconds to path prefix if grain is hours or lower

### ISSUE THREAD

**Issue by luisvicenteatprima** [crowemi/target-s3#20]
I don't know if it's intentional but:

https://github.com/crowemi/target-s3/blob/709734e20932039ebf3573e89019912e343fc027/target_s3/formats/format_base.py#L135 

Means that seconds are always added when the grain is hour or lower

**Comment by crowemi** [comment]
Yeah! Looks like we need to change that `4` to a `2`

**Comment by luisvicenteatprima** [comment]
I don't mind to open a quick PR

**Comment by crowemi** [comment]
That would be very helpful! Thank you 😄
