### ISSUE TITLE
parquet schema wrongly inferred

### ISSUE THREAD

**Issue by prakharcode** [crowemi/target-s3#23]
if there's a nested object that is sparse in nature, meaning occurs infrequently in data. Then for that data the inferred schema would be wrong.

eg. 
correct schema: ["attributes"]["teams"]["assigned"] = list<item: struct<email: string>>> 
but if there's no data for the above attributes, due to how schema is currently inferred [here](https://github.com/crowemi/target-s3/blob/a8f9cd988a315a34cd92152c8aaa1f0ccb29e1ec/target_s3/formats/format_parquet.py#L168) the schema becomes:
list<item: null> which can be tricky if the files are then being loaded to spark for downstream consumption.

I see there's a comment already to build schema from json schema rather than inferring it which I believe is the right way.

Just opening this issue, so I can pick it up later.

**Comment by crowemi** [comment]
Hey @prakharcode 👋 -- yes, I believe this is the same as #17. You could check out this [branch](https://github.com/crowemi/target-s3/tree/17) which has some starter code for validating and creating the data fame based on inputs. I never quite got it where I wanted it.
