### ISSUE TITLE
config credentials not used yet

### ISSUE THREAD

**Issue by pnadolny13** [crowemi/target-s3#3]
I noticed that I can set credentials in the config but they arent used anywhere yet. Setting them in the environment does seem to work.

**Comment by crowemi** [comment]
Yes -- this hasn't been configured yet as we're currently pulling these values from the local environment at runtime. I believe we just need to update the session [here](https://github.com/crowemi/target-s3/blob/main/target_s3/formats/format_base.py#L45-L48)
