### ISSUE TITLE
bug: `PermanentRedirect Message`

### ISSUE THREAD

**Issue by pnadolny13** [crowemi/target-s3#4]
I'm getting the following error when I try to use the parquet format type:

```
AWS Error UNKNOWN (HTTP status 301) during CreateMultipartUpload operation: Unable to parse ExceptionName: PermanentRedirect Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

It looks like in [this commit](https://github.com/crowemi/target-s3/commit/7f7610a092b539b763fee5c67d8d324d3f8fe48f) the logic for creating a file system changed. If I put it back to what it was I'm able to get it to work. I think the error is related to the region not properly being set 

Also if I'm reading it correctly I think [self.session](https://github.com/crowemi/target-s3/blob/6dcf59f9b4746717b8abf73ca8d66f8e1e72079c/target_s3/formats/format_base.py#L45) gets instantiated on init each time so its never possible to get to https://github.com/crowemi/target-s3/blob/6dcf59f9b4746717b8abf73ca8d66f8e1e72079c/target_s3/formats/format_parquet.py#L30, is that right?

**Comment by crowemi** [comment]
Yes -- you're right, `session` will always evaluate to `True`. So, we probably just need to add `aws_region` to the file system instantiation [here](https://github.com/crowemi/target-s3/blob/main/target_s3/formats/format_parquet.py#L25C11-L28)

```
self.file_system = fs.S3FileSystem(
    access_key=self.session.get_credentials().access_key,
    secret_key=self.session.get_credentials().secret_key,
    session_token=self.session.get_credentials().token
)
```
